##############################################
#               UESL MiniGames               #
##############################################
#Config for Plugin

##############################################
#                 Paintball                  #
##############################################
#Paintball Arena Map:
paintball_arena: arena1
paintball_start_command: paintball join arena1
paintball_end_command: paintball leave
paintball_max_player_count: 10
#Paintball Message (support for & colours):
paintball_message: Joining Paintball
paintball_rule: Points are based of Kills and if you Win
#Prize (Points):
paintball_win: 10
paintball_lose_disadvantage: 2
paintball_tie: 5
paintball_points_per_kills: 1
##############################################
#                   Spleef                   #
##############################################
#Spleef Arena Map
spleef_arena: DeathSpleef
spleef_start_command: spleef join DeathSpleef
spleef_end_command: spleef leave
spleef_max_player_count: 6
#Spleef Message (support for & colours):
spleef_message: Joining Parkour
spleef_rule: Points are based of CheckPopints and if you Finish
#Prize (Points):
spleef_first: 5
##############################################
#                   TNTRun                   #
##############################################
#TNTRun Arena Map
tntrun_arena: arena1
tntrun_start_command: tntrun join arena1
tntrun_end_command: tntrun leave
tntrun_max_player_count: 24
#TNTRun Message (support for & colours):
tntrun_message: Joining TNTRun
tntrun_rule: Points are based of if you Win
#Prize (Points):
tntrun_first: 10
tntrun_second: 7
tntrun_third: 5
##############################################
#                  Parkour                   #
##############################################
#Parkour Arena Map
parkour_arena: parkoursnake
parkour_start_command: pa join parkoursnake
parkour_end_command: pa leave
parkour_timer: 600
parkour_max_player_count: 24
#Parkour Message (support for & colours):
parkour_message: Joining Parkour
parkour_rule: Points are based of CheckPopints and if you Finish
#Prize (Points):
parkour_first: 10
parkour_second: 7
parkour_third: 5
parkour_finish: 3
parkour_points_per_checkpoint: 1
##############################################
#               Build Battle                 #
##############################################
#buildbattle Arena Map
buildbattle_arena: Solo
buildbattle_start_command: buildbattle join Solo
buildbattle_end_command: buildbattle leave
buildbattle_max_player_count: 6
#buildbattle Message (support for & colours):
buildbattle_message: Joining Build Battle
buildbattle_rule: Points are based of Votes and if you Win
#Prize (Points):
buildbattle_first_bonus: 10
buildbattle_points_per_point: 1
##############################################
#                  BedWars                   #
##############################################
#BedWars Arena Map
bedwars_arena: Castle-Defenders
bedwars_start_command: bedwars join Castle-Defenders
bedwars_end_command: bedwars leave
bedwars_max_player_count: 12
#BedWars Message (support for & colours):
bedwars_message: Joining BedWars
bedwars_rule: Points are based of Kills and if you Win
#Prize (Points):
bedwars_first: 10
bedwars_points_per_kills: 1
bedwars_points_per_bed: 5
##############################################
#                HungerGames                 #
##############################################
#HungerGames Arena Map:
hungergames_arena: breeze2
hungergames_start_command: hg join breeze2
hungergames_end_command: hg leave
hungergames_max_player_count: 24
#HungerGames Message (support for & colours):
hungergames_message: Joining HungerGames
hungergames_rule: Points are based of Kills and if you Win
#Prize (Points):
hungergames_first: 10
hungergames_second: 7
hungergames_third: 5
hungergames_points_per_kills: 1
##############################################
#                   Global                   #
##############################################
#Finishing Ceremony
#First Place Timer
first_timer: 19
#Second Place Timer
second_timer: 12
#Third Place Timer
third_timer: 5
#Messages
first_place_message: "Finally with &e%uesl-minigames_points% &rpoints is &1%uesl-minigames_points1%"
second_place_message: "2nd place with &e%uesl-minigames_points% &rpoints is &1%uesl-minigames_points2%"
third_place_message: "3rd place with &e%uesl-minigames_points% &rpoints is &1%uesl-minigames_points3%"
welcome_message: "Welcome to the Finishing Ceremony!"
#Lobby Location
Lobby:
  ==: org.bukkit.Location
  world: World
  x: 0.0
  y: 8.0
  z: 0.0
  pitch: 0.0
  yaw: 90.0
#Winner Location
first_place:
  ==: org.bukkit.Location
  world: World
  x: -433.5
  y: 17.0
  z: 157.5
  pitch: 0.0
  yaw: -90.0
second_place:
  ==: org.bukkit.Location
  world: World
  x: -433.5
  y: 14.0
  z: 166.5
  pitch: 0.0
  yaw: -90.0
third_place:
  ==: org.bukkit.Location
  world: World
  x: -433.5
  y: 11.0
  z: 148.5
  pitch: 0.0
  yaw: -90.0
spectators:
  ==: org.bukkit.Location
  world: World
  x: -407.0
  y: 12.0
  z: 157.0
  pitch: 0.0
  yaw: 90.0
